name: SimpleTag
main: com.civservers.simple_tag.simpletag.SimpleTag
#com.example.plugins.MyPlugin
version: 0.1.1b

author: "Civalo"
commands:
   simpletag:
      description: This is a demo command. (no requirements)
      aliases: [stag]
      usage: 
permissions:
   simpletag.create:
      description: Allows the use of start / end / kick commands to create and manage games.
      default: op
   simpletag.play:
      description: Allows the use of join / leave comamnds to play existing games.
      default: op
   simpletag.admin:
      description: Allows use of reload and endAll comamnds.
      default: op